name: 1 - hello - world

on: push

jobs:
    first-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Print hello
              run: echo "Hello World"

            - name: Print Goodbye
              run: echo "Goodbye"